### ISSUE TITLE
在macOS下显示失败，能更新下吗？

### ISSUE THREAD

**Issue by fogeen** [gjiazhe/Up-Down#4]

**Comment by gjiazhe** [comment]
能否具体说明一下
1、你的设备，系统版本
2、显示失败是什么意思，打不开app么？还是有提示什么信息？
谢谢。

**Comment by fogeen** [comment]
1，MBP Early 2015   macOS sierra 10.12beta（16A313a）
2，可以打开 APP，但是在状态栏不显示网速数字。
叨扰了，感谢！

**Comment by gjiazhe** [comment]
唔~ 那感觉有可能是beta版的原因……

是这样，我不打算把系统升级到beta版，
所以只能等月底正式版出来，我升级之后才能帮你看一下这个问题了。

**Comment by fogeen** [comment]
好的，多谢🙏

**Comment by Binlogo** [comment]
正式版更新了，也有这个问题

**Comment by Binlogo** [comment]
Sierra 系统下 /usr/bin 目录下没有了 sar 命令

**Comment by qfdk** [comment]
@gjiazhe @Binlogo 同样出现此问题 还以为是编译问题 新版xcode 编译之后还是有问题 看到ls说是缺少文件
下载sar的源码 编译不过去郁闷。找来了低版本的sar无法运行。。

**Comment by ChengLuffy** [comment]
使用**Xcode8**自动迁移到**swift3.0**后，工程在 `NetWorkMonitor.swift:23` 

```
func startUpdateTimer() {
        Timer.scheduledTimer(timeInterval: 2, target: self, selector: #selector(updateNetWorkData), userInfo: nil, repeats: true)
        RunLoop.current.run()
    }
```

`RunLoop.current.run()` 处崩溃。
信息如下：

> **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'

**Comment by raykle** [comment]
正式版已经出来了啊， @gjiazhe 有准备更新么？🙏

**Comment by gjiazhe** [comment]
实在很抱歉🙏，最近一段时间一直在准备秋招，所以可能要跳票了。
而且这个问题貌似有些棘手，因为MacOS里面直接删了sar，而up&down基于sar的。
如果能找到安装sar的方法最好不过，如果不行，我会再想其他的方式，但是最近确实没有时间可以做这件事，非常抱歉。

**Comment by qfdk** [comment]
@gjiazhe https://github.com/sysstat/sysstat 这是开源的一个sar， mac编译通过，但是运行出来没有结果。。

**Comment by ChengLuffy** [comment]
昨天进行了了解，原作者说自己没有Mac，无能为力，https://github.com/sysstat/sysstat/issues/74
在 2016年9月29日，15:02，qfdk <notifications@github.com<mailto:notifications@github.com>> 写道：

@gjiazhehttps://github.com/gjiazhe https://github.com/sysstat/sysstat 这是开源的一个sar， mac编译通过，但是运行出来没有结果。。

**Comment by gjiazhe** [comment]
抱歉了大家，前阵子在忙别的事情。
这几天我会开始修复这个问题，目前打算改用nettop代替sar。

**Comment by gjiazhe** [comment]
已修复，你们看看能不能用。
再次谢谢大家的反馈！

**Comment by Binlogo** [comment]
辛苦啦~  这就试试~！
