### ISSUE TITLE
提交一个sar

### ISSUE THREAD

**Issue by qfdk** [gjiazhe/Up-Down#5]
这个项目没有sar 似乎就没法跑起来，于是去找源码。
mac os 开源了一部分源码
[下载地址 10,11](http://opensource.apple.com/tarballs/system_cmds/system_cmds-671.10.3.tar.gz)
使用方法，解压，进去sar文件夹，执行命令编译

``` shell
cc -Wall -I. -I ../sadc.tproj -O -o  sar sar.c
```

编译通过
<img width="808" alt="2016-10-09 21 40 59" src="https://cloud.githubusercontent.com/assets/2404478/19223163/1c7a64ca-8e69-11e6-970d-f9e287abfe04.png">

**Comment by oa414** [comment]
我的 OS X 10.11 下就有  /usr/bin/sar ...

**Comment by qfdk** [comment]
@oa414 给10.12用的

**Comment by qinyuhang** [comment]
那个是不行的。。。 我在 ss-libev 里面加了 log traffic 的 宏，https://github.com/qinyuhang/shadowsocks-libev/tree/traffic-status 可以从构架上改造一下，让这个 traffic log 变成网速显示（只显示走SS的网速）。
