### ISSUE TITLE
Apps keeps closing by itself

### ISSUE THREAD

**Issue by jenil** [gjiazhe/Up-Down#9]
Does anyone else experience the app stop by itself after some time?

**Comment by yzlnew** [comment]
Same problem here.

**Comment by wtry** [comment]
+1

**Comment by jimut** [comment]
How did you solve it? I am facing the same issue.

**Comment by wtry** [comment]
> How did you solve it? I am facing the same issue.

https://mac.gj.qq.com/

**Comment by jimut** [comment]
@wtry Need it in English 😓
